@echo off
cd .venv2\Scripts
call activate.bat
cd ../..
cd Projects
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=4 COMPRESSION_METHOD=3 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=4 COMPRESSION_METHOD=4 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
cmd /k 