@echo off
cd .venv2\Scripts
call activate.bat
cd ../..
cd Projects
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy FP_BITS=2 NUM_EPOCHS=320000 COMPRESSION_METHOD=4 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5 TF_USE_TRI_PE=False TF_USE_MISS_QUANTIZE=True
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy FP_BITS=2 NUM_EPOCHS=320000 COMPRESSION_METHOD=4 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5 TF_USE_TRI_PE=False TF_USE_MISS_QUANTIZE=False
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy FP_BITS=2 NUM_EPOCHS=320000 COMPRESSION_METHOD=4 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5 TF_USE_TRI_PE=True TF_USE_MISS_QUANTIZE=True
cmd /k 