@echo off
cd .venv2\Scripts
call activate.bat
cd ../..
cd Projects

python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=2 COMPRESSION_METHOD=2 IMAGE_DIMENSION=3 IMAGE_SIZE=512 CROP_MIP_LEVEL=8
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=2 COMPRESSION_METHOD=3 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=2 COMPRESSION_METHOD=4 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=2 COMPRESSION_METHOD=5 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=3 COMPRESSION_METHOD=2 IMAGE_DIMENSION=3 IMAGE_SIZE=512 CROP_MIP_LEVEL=8
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=3 COMPRESSION_METHOD=3 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=3 COMPRESSION_METHOD=4 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=3 COMPRESSION_METHOD=5 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=1 COMPRESSION_METHOD=2 IMAGE_DIMENSION=3 IMAGE_SIZE=512 CROP_MIP_LEVEL=8
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=1 COMPRESSION_METHOD=3 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=1 COMPRESSION_METHOD=4 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5
python image_compression.py IMAGE_PATH=data/Multilayer_para3_64.npy IMAGE_DTYPE=ndarray NUM_EPOCH=100000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=1 COMPRESSION_METHOD=5 IMAGE_DIMENSION=3 IMAGE_SIZE=64 CROP_MIP_LEVEL=5

python image_compression.py IMAGE_PATH=data/sancho_512.png IMAGE_DTYPE=image NUM_EPOCH=1000 FP_G0_BIT=2 FEATURE_PYRAMID_G0_CHANNEL=8 FP_G1_BIT=4 FEATURE_PYRAMID_G1_CHANNEL=12 FEATURE_PYRAMID_SIZE_RATE=2 COMPRESSION_METHOD=1 IMAGE_DIMENSION=2 IMAGE_SIZE=512 CROP_MIP_LEVEL=8
cmd /k 